myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/posts/forms.py
from django import forms
from .import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.post
        fields =['title','body','slug','banner' ]

myproject/myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse("hellp World! I'm Home")
    return render(request, 'home.html')

def about(request):
    #return HttpResponse("My about page,")
    return render(request, 'about.html')

myproject/posts/views.py
from django.shortcuts import render, redirect
from .models import post 
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def posts_list(request):
    posts = post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts':posts})

def  post_page(request, slug):
    posts = post.objects.get(slug=slug)
    return render(request, 'posts/posts_page.html', {'post':posts})

@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form": form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

myproject/posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}
    New Post Page
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Add Post </button>
        </form>
    </section>
{% endblock %}

myproject/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title}}
{% endblock %}

{% block content %}
    <section>
        <h1> {{ post.title}}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
            
        
    </section>
    
{% endblock %}

myproject/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Posts List
{% endblock %}

{% block content %}
    <section>
        <h1 style="color: red;">Resources</h1>
        <p style="color: blue;">Resources will populate the area below</p>
        <p style="color: blue;">⚡</p>
        <hr>

        {% for post in posts %}
            <article class="flex-container">
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                        {{ post.title}}
                    </a>
                </h2>
                <p>{{ post.date }} by {{ post.author }}</p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor %}
    </section>
    
{% endblock %}

myproject/posts/templates/posts/posts_page.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title}}
{% endblock %}

{% block content %}
    <section>
        <img 
            class="banner"
            src="{{ post.banner.url }}"
            alt="{{ post.title }}"
        />
        <h1> {{ post.title}}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
        
            
        
    </section>
    
{% endblock %}

myproject/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
    <hr>
    <div>
        <div class="bg-body-tertiaryp-5 rounded">
          <div class="col-sm-8 mx-auto">
            <h1>About DevDive</h1>
            <p>This example is a quick exercise to illustrate how the About page and its contents work. Some navbars extend the width of the viewport, others are confined within a <code>.container</code>. For positioning of content in the About page, checkout the Bootstrap Docs.</p>
            <p>At the smallest breakpoint, the collapse plugin is used to hide the links and show a menu button to toggle the collapsed content.</p>
            <p>
              <a class="btn btn-primary" href="/" role="button">Home &raquo;</a>
            </p>
          </div>
        </div>
      </div>

{% endblock %}

myproject/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock %}

{% block content %}
        <h1>Home</h1>
        <p>Check out my <a href="/about">About</a> page.</p>

        <hr>
        <div>
            <div class="bg-body-tertiaryp-5 rounded">
              <div class="col-sm-8 mx-auto">
                <h1>Welcome to DevDive Resource Platform</h1>
                <p>Please proceed to <a href="{% url 'users:register' %}">create your account</a> and publish a post or a resource</p>
                <p>This example is a quick exercise to illustrate how the Home page and its contents work. Some navbars extend the width of the viewport, others are confined within a <code>.container</code>. For positioning of content in the Home page, checkout the Bootstrap Docs.</p>
                <p>At the smallest breakpoint, the collapse plugin is used to hide the links and show a menu button to toggle the collapsed content.</p>
                <p>
                  <a class="btn btn-primary" href="/about" role="button">About &raquo;</a>
                </p>
              </div>
            </div>
          </div>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
     {% comment %} <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <script src="{% static 'js/main.js' %}" defer></script>


    <style>
        .navbar-brand img {
            height: 40px;
            width: auto;
        }
        .nav-buttons .btn {
            margin-left: 10px;
        }
    </style>

</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <!-- Logo -->
            <a class="navbar-brand" href="#">
                <img src="static/img/DevDiveFaveicon.png" alt="DevDive">
            </a>
            <!-- Navbar toggler for smaller screens -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:list' %}">Resources Feed</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'posts:new-post' %}"><i class="bi bi-file-earmark-plus"></i> Create Post</a>
                        </li>
                    {% else %} 

                    
                    {% endif %}
                </ul>
                <!-- Login and Signup buttons -->
                <div class="nav-buttons d-flex">
                    {% if user.is_authenticated %}
                        {% comment %} <a href="{% url 'users:logout' %}" class="btn btn-outline-primary">Logout</a> {% endcomment %}

                        <form  action="{% url 'users:logout' %}" method="post">
                            {% csrf_token %} 
                            <button class="btn btn-outline-primary" aria-label="User Logout" title="User Logout">Logout</button>
                        </form>
                    {% else %}
                        <a href="{% url 'users:login' %}" class="btn btn-outline-primary">Login</a>
                        <a href="{% url 'users:register' %}" class="btn btn-primary">Signup</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    

        {% block content %}

        {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

myproject/users/templates/users/login.html
{% extends "layout.html" %}

{% block title %}
    User Login
{% endblock %}

{% block content %}
   
    <h1>User Login</h1>
    <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <button class="form-submit">Submit</button>
    </form>

    
{% endblock %}

myproject/users/templates/users/register.html
{% extends "layout.html" %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
   
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>

    
{% endblock %}